sonar.projectKey=gudang-kita
sonar.projectName=Gudang Kita
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=app,config,public,views
sonar.tests=tests
sonar.exclusions=vendor/**,database/**,public/assets/**
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.coverage.exclusions=app/Controller/**,app/Repository/**,app/Security/**,app/Support/**,app/bootstrap.php,config/**,public/**,views/**
